# Generated by Django 2.0.7 on 2018-07-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
    ]
