# Generated by Django 2.0.7 on 2018-07-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0002_accounts_computerscience_english_maths_science_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='english',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='maths',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='science',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Student', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Sub1',
            field=models.CharField(choices=[('E', 'English'), ('M', 'Math'), ('S', 'Science'), ('C', 'ComputerScience'), ('A', 'Accounts')], default='select subject', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Sub2',
            field=models.CharField(choices=[('E', 'English'), ('M', 'Math'), ('S', 'Science'), ('C', 'ComputerScience'), ('A', 'Accounts')], default='select subject', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Sub3',
            field=models.CharField(choices=[('E', 'English'), ('M', 'Math'), ('S', 'Science'), ('C', 'ComputerScience'), ('A', 'Accounts')], default='select subject', max_length=20),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Sub4',
            field=models.CharField(choices=[('E', 'English'), ('M', 'Math'), ('S', 'Science'), ('C', 'ComputerScience'), ('A', 'Accounts')], default='select subject', max_length=20),
        ),
    ]
