# Generated by Django 2.0.7 on 2018-07-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0003_auto_20180719_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Maths',
            new_name='Math',
        ),
    ]
