# Generated by Django 2.0.7 on 2018-07-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0004_auto_20180721_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Teacher', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='computerscience',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Teacher', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='english',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Teacher', verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='math',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Teacher', verbose_name='teacher'),
        ),
    ]
