# Generated by Django 2.0.7 on 2018-07-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0005_auto_20180722_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapps.Teacher', verbose_name='teacher'),
        ),
    ]
